-intstyle "ise" -incremental -lib "secureip" -o "D:/VM/Partilha/P1/Proj1/rom_descodificacao_TB_isim_beh.exe" -prj "D:/VM/Partilha/P1/Proj1/rom_descodificacao_TB_beh.prj" "work.rom_descodificacao_TB" 
